Repository GenshinAcademy/GenshinAcademyCore, pull requests merged in 2023-04, with the labels that each got.

#18 Added automatic save for all association fields in QueryBuilder.
  internal/db_postgres/repositories/querybuilder.go
Labels: database

#29 Project cleaning
  .github/workflows/test_on_pr.yaml
  cmd/web/main.go
  internal/services/genshin/characters/service.go
  internal/services/middlewares/auth.go
  internal/services/news/service.go
  internal/services/tables/service.go
  internal/services/weasel/appraiser/mappers.go
  internal/services/weasel/appraiser/service.go
  internal/services/weasel/appraiser/web_models/character.go
  internal/services/weasel/appraiser/web_models/stats_profit.go
  scripts/download_data.sh
Labels: enhancement

#32 Add limit offset to api enpoints
  cmd/web/main.go
  internal/academy_core/models/news.go
  internal/academy_core/models/table.go
  internal/academy_core/repositories/find_parameters/news.go
  internal/academy_core/repositories/find_parameters/table.go
  internal/db_postgres/mappers/mappers.go
  internal/db_postgres/repositories/querybuilder.go
  internal/services/genshin/characters/service.go
  internal/services/middlewares/query.go
  internal/services/news/models/models.go
  internal/services/news/service.go
  internal/services/tables/models/models.go
  internal/services/tables/service.go
  internal/services/weasel/appraiser/mappers.go
  internal/services/weasel/appraiser/models/character.go
  internal/services/weasel/appraiser/models/stats_profit.go
  internal/services/weasel/appraiser/service.go
  pkg/genshin_core/repositories/find_parameters/character.go
  pkg/genshin_core/repositories/find_parameters/find_parameters.go
Labels: api
